-- Sourced, dated Explore issues are stored in Supabase and become active
-- from their week_start date. The client only reads published sessions.
create table if not exists public.explore_weekly_sessions (
  week_start date primary key,
  title text not null check (length(btrim(title)) between 1 and 160),
  summary text not null check (length(btrim(summary)) between 1 and 500),
  items jsonb not null check (jsonb_typeof(items) = 'array'),
  status text not null default 'published' check (status in ('draft', 'published')),
  created_at timestamptz not null default now(),
  check (extract(isodow from week_start) = 1)
);

alter table public.explore_weekly_sessions enable row level security;
grant select on public.explore_weekly_sessions to anon, authenticated;
grant all on public.explore_weekly_sessions to service_role;
drop policy if exists explore_weekly_sessions_read_published on public.explore_weekly_sessions;
create policy explore_weekly_sessions_read_published
  on public.explore_weekly_sessions for select to anon, authenticated
  using (status = 'published');

insert into public.explore_weekly_sessions (week_start, title, summary, items, status)
values (
  date '2026-10-12',
  'From cells to clinical evidence',
  'Three foundational concepts, two mechanism-to-clinic connections and two recent randomized trials, with sources and limits shown on every card.',
  $items$[
    {
      "id":"weekly-20261012-concept-surfactant","category":"concept","topic":"Respiratory physiology","title":"How surfactant helps the lungs exchange gases","summary":"A thin film lowers surface tension so alveoli are easier to expand and less likely to collapse during exhalation.","basicIdea":"Type II alveolar cells make pulmonary surfactant, a lipoprotein mixture that spreads along the air-liquid lining. It lowers surface tension, reducing the inward force that would otherwise make small alveoli harder to keep open. Oxygen and carbon dioxide then diffuse across the thin alveolar-capillary interface.","whyItMatters":"Low surfactant is one contributor to respiratory distress in premature newborns. This links a microscopic surface property to the mechanics of breathing and gas exchange; alveoli are not literal balloons, and surfactant supports rather than powers each breath.","provenance":{"status":"reviewed","note":"Supplementary physiology explainer checked against the linked references. Not treatment advice or authoritative course material."},"sources":[{"title":"Physiology, Alveolar Tension — NCBI Bookshelf","url":"https://www.ncbi.nlm.nih.gov/books/NBK539825/"},{"title":"How the Lungs Work — NHLBI","url":"https://www.nhlbi.nih.gov/health/lungs/respiratory-system"}],"publishedAt":"2026-10-12","featured":false,"tags":["respiratory","alveoli","surfactant","gas exchange"]
    },
    {
      "id":"weekly-20261012-concept-raas","category":"concept","topic":"Renal physiology","title":"How kidneys conserve salt and water through RAAS","summary":"A kidney-sensed signal starts a hormone relay that influences vessel tone, sodium handling and blood volume.","basicIdea":"Reduced renal perfusion, reduced sodium-chloride delivery at the macula densa, or sympathetic beta-1 stimulation can increase renin release. Renin begins a cascade that produces angiotensin II, which constricts vessels and stimulates aldosterone. Aldosterone increases sodium reabsorption and potassium secretion in the distal nephron; water balance also depends on vasopressin and other controls.","whyItMatters":"RAAS connects kidney sensing to blood-vessel tone and salt balance. It offers a slower hormonal counterpart to the rapid baroreflex already featured in Explore. Persistent or dysregulated RAAS activity can contribute to disease, so the response is not always beneficial.","provenance":{"status":"reviewed","note":"Supplementary physiology explainer checked against the linked references. Not a diagnostic or treatment guide."},"sources":[{"title":"Physiology, Renin Angiotensin System — NCBI Bookshelf","url":"https://www.ncbi.nlm.nih.gov/books/NBK470410/"},{"title":"Physiology, Aldosterone — NCBI Bookshelf","url":"https://www.ncbi.nlm.nih.gov/books/NBK470339/"}],"publishedAt":"2026-10-12","featured":false,"tags":["kidney","RAAS","aldosterone","blood pressure"]
    },
    {
      "id":"weekly-20261012-concept-immunologic-memory","category":"concept","topic":"Immunology","title":"How immune memory prepares for a later infection","summary":"After an antigen-specific response, memory B and T cells can respond faster on a later encounter.","basicIdea":"Adaptive immune responses can leave antigen-specific memory B cells and T cells. On re-exposure, memory B cells can rapidly generate antibody-secreting cells, while memory T cells help coordinate responses or act against infected cells. Vaccines train immune recognition without requiring a person to experience the disease itself.","whyItMatters":"This explains why a later immune response may be faster and how vaccination can build active immunity. Memory does not guarantee that infection will be prevented, and its duration and strength vary by vaccine, pathogen and host.","provenance":{"status":"reviewed","note":"Supplementary immunology explainer checked against the CDC reference. It does not describe vaccine schedules or recommend a vaccine."},"sources":[{"title":"Chapter 1: Principles of Vaccination — CDC Pink Book","url":"https://www.cdc.gov/pinkbook/hcp/table-of-contents/chapter-1-principles-of-vaccination.html"}],"publishedAt":"2026-10-12","featured":false,"tags":["immunology","memory B cells","memory T cells","vaccination"]
    },
    {
      "id":"weekly-20261012-connection-insulin-potassium","category":"connection","topic":"Endocrinology → clinical physiology","title":"Why insulin can shift potassium into cells","summary":"Insulin-driven cellular potassium uptake helps explain why blood potassium and total-body potassium can tell different stories in diabetic ketoacidosis.","basicIdea":"Insulin can stimulate cellular potassium uptake, in part through effects on Na+/K+-ATPase. In diabetic ketoacidosis, urinary and gastrointestinal losses can deplete total-body potassium even when a measured serum concentration is normal or high. Insulin and fluid treatment can then lower the measured serum concentration as potassium shifts and losses continue to be managed.","whyItMatters":"The mechanism links hormone signaling to electrolyte interpretation and shows why an extracellular concentration is not the same as total-body stores. DKA treatment requires repeated clinical and laboratory assessment; this explainer is not a treatment protocol.","provenance":{"status":"reviewed","note":"Supplementary mechanism-to-clinic summary checked against the linked physiology and consensus references. Not treatment advice."},"sources":[{"title":"Regulatory effect of insulin on Na+/K+-ATPase — PMC","url":"https://pmc.ncbi.nlm.nih.gov/articles/PMC8438676/"},{"title":"Hyperglycemic Crises in Patients With Diabetes — Diabetes Care consensus statement","url":"https://diabetesjournals.org/care/article/24/1/131/21107/Management-of-Hyperglycemic-Crises-in-Patients"}],"publishedAt":"2026-10-12","featured":false,"tags":["insulin","potassium","DKA","electrolytes"],"connectionSteps":[{"label":"Insulin signal","detail":"Insulin can increase cellular potassium uptake through ion-transport mechanisms."},{"label":"Whole-body balance","detail":"DKA can cause potassium loss in urine and other fluids."},{"label":"Lab interpretation","detail":"Serum concentration reflects the extracellular compartment, not all potassium stores."},{"label":"Clinical link","detail":"A normal or high measured serum value does not rule out total-body depletion; monitoring matters during treatment."}]
    },
    {
      "id":"weekly-20261012-connection-aspirin-platelets","category":"connection","topic":"Haematology → vascular biology","title":"Why aspirin's platelet effect can outlast the drug","summary":"Irreversible inhibition of platelet cyclooxygenase can persist after aspirin itself has left the bloodstream.","basicIdea":"Aspirin acetylates platelet cyclooxygenase-1 and reduces thromboxane A2 production, which normally amplifies platelet activation. Platelets have limited ability to replace irreversibly inhibited enzyme, so the effect on an exposed platelet can outlast aspirin's presence in plasma.","whyItMatters":"This connects a short-lived medicine to a longer-lived change in platelet function and helps explain an antiplatelet mechanism. Whether aspirin is appropriate depends on an individual indication and bleeding risk; this is not advice to start or stop it.","provenance":{"status":"reviewed","note":"Supplementary mechanism summary checked against biochemical and clinical sources. Not medication advice."},"sources":[{"title":"Aspirin acetylation of platelet proteins — PubMed","url":"https://pubmed.ncbi.nlm.nih.gov/1159076/"},{"title":"Aspirin acetylation of prostaglandin synthase — PNAS","url":"https://www.pnas.org/doi/10.1073/pnas.72.8.3073"},{"title":"ISIS-2 Collaborative Group — PubMed","url":"https://pubmed.ncbi.nlm.nih.gov/2899772/"}],"publishedAt":"2026-10-12","featured":false,"tags":["aspirin","platelets","COX-1","thrombosis"],"connectionSteps":[{"label":"Drug target","detail":"Aspirin irreversibly acetylates platelet COX-1."},{"label":"Mediator","detail":"Lower COX-1 activity reduces thromboxane A2 production."},{"label":"Cell lifespan","detail":"Platelets cannot readily replace the inhibited enzyme."},{"label":"Clinical link","detail":"Platelet effects can persist after aspirin has cleared; treatment decisions still depend on indication and bleeding risk."}]
    },
    {
      "id":"weekly-20261012-research-prtk03","category":"research","topic":"Oncology · gene therapy","title":"An investigational gene therapy added to radiotherapy for localized prostate cancer","summary":"A 2026 phase 3 trial reported longer disease-free survival, while an overall-survival benefit was not established at this analysis.","basicIdea":"PrTK03 was a randomized, double-blind, placebo-controlled phase 3 trial at 51 US and Puerto Rico centres. It enrolled 745 men with intermediate- or high-risk localized prostate cancer receiving external-beam radiotherapy, with optional short-course androgen-deprivation therapy. Participants received investigational aglatimagene besadenovec (CAN-2409) plus valacyclovir or placebo plus valacyclovir.","whyItMatters":"The primary composite of recurrence or death from any cause favored the investigational group after median follow-up of 50.3 months (hazard ratio 0.70; 95% CI 0.52–0.94). Overall survival was similar in this analysis (hazard ratio 1.18; 95% CI 0.64–2.15), with few prostate-cancer deaths; longer follow-up is needed.","provenance":{"status":"reviewed","note":"Summary of a peer-reviewed randomized trial, checked against the published report. Investigational therapy; not a treatment recommendation."},"sources":[{"title":"PrTK03 phase 3 trial — The Lancet Oncology (2026)","url":"https://pmc.ncbi.nlm.nih.gov/articles/PMC13437160/"},{"title":"PubMed record","url":"https://pubmed.ncbi.nlm.nih.gov/42225101/"}],"publishedAt":"2026-10-12","featured":false,"tags":["phase 3","randomized trial","prostate cancer","gene therapy"],"research":{"evidenceType":"Phase 3 randomized, double-blind, placebo-controlled trial","whatWeKnow":"The primary disease-free-survival composite favored aglatimagene plus valacyclovir (HR 0.70; 95% CI 0.52–0.94; p=0.016). Overall survival was not significantly different at this analysis (HR 1.18; 95% CI 0.64–2.15).","whatRemainsUncertain":"Overall-survival follow-up is immature, and these findings apply to the studied intermediate/high-risk localized disease population receiving radiotherapy. The therapy remains investigational; the study does not establish a benefit for other populations or treatment settings."}
    },
    {
      "id":"weekly-20261012-research-discount","category":"research","topic":"Neurology · stroke","title":"Thrombectomy for medium or distal vessel stroke: the DISCOUNT trial","summary":"The trial did not demonstrate improved three-month functional outcomes in its selected population and reported more symptomatic hemorrhage with thrombectomy.","basicIdea":"DISCOUNT randomized 244 people with acute ischemic stroke from a primary, isolated medium or distal arterial occlusion at 22 French stroke centres. The trial stopped at an interim analysis after enrolling about half of its planned 488 participants, following a recommendation based on futility and increased symptomatic intracranial hemorrhage.","whyItMatters":"At three months, good functional outcome (modified Rankin score 0–2) occurred in 62% of the thrombectomy group and 68% of the medical-treatment group (odds ratio 0.73; 95% CI 0.40–1.31). Symptomatic intracranial hemorrhage was 11% versus 3%. The early stop leaves uncertainty, and this result should not be generalized to large-vessel occlusion or every stroke presentation.","provenance":{"status":"reviewed","note":"Summary of a peer-reviewed randomized clinical trial, checked against the published report. Not clinical guidance."},"sources":[{"title":"DISCOUNT randomized clinical trial — JAMA (2026)","url":"https://jamanetwork.com/journals/jama/article-abstract/2851954"}],"publishedAt":"2026-10-12","featured":false,"tags":["randomized clinical trial","ischemic stroke","thrombectomy","neurology"],"research":{"evidenceType":"Randomized clinical trial; stopped early at interim analysis","whatWeKnow":"In 244 randomized participants, good three-month functional outcome was 62% with thrombectomy and 68% with medical treatment alone. Symptomatic intracranial hemorrhage was 11% in those receiving thrombectomy versus 3% in those who did not.","whatRemainsUncertain":"The trial stopped after 244 of 488 planned participants, reducing precision. Results concern the trial's selected medium/distal occlusion population and do not settle treatment effects in other stroke settings."}
    }
  ]$items$::jsonb,
  'published'
)
on conflict (week_start) do update set
  title = excluded.title,
  summary = excluded.summary,
  items = excluded.items,
  status = excluded.status;
